import { type SourceManifest, SourceManifestSchema } from "@biosecurity/contracts";

const manifest = (value: SourceManifest): SourceManifest => SourceManifestSchema.parse(value);

export const INITIAL_SOURCE_MANIFESTS: SourceManifest[] = [
  manifest({
    id: "who-don",
    name: "WHO Disease Outbreak News",
    sourceClass: "authority",
    geographicCoverage: ["global"],
    languages: ["en", "fr", "ar", "zh", "es", "ru"],
    dataEventTypes: ["outbreak notices"],
    accessMethod: "official web feed and document retrieval",
    authenticationRequirements: "none",
    cadence: "daily",
    typicalDelay: "publication dependent",
    licence: "WHO site terms",
    redistributionPermission: "metadata and lawful excerpts only",
    commercialUseStatus: "verify WHO terms",
    knownLimitations: ["Not a comprehensive event inventory"],
    health: "available",
  }),
  manifest({
    id: "ukhsa-dashboard",
    name: "UKHSA data dashboard",
    sourceClass: "authority",
    geographicCoverage: ["United Kingdom"],
    languages: ["en"],
    dataEventTypes: ["public health surveillance"],
    accessMethod: "public API",
    authenticationRequirements: "none",
    cadence: "dataset dependent",
    typicalDelay: "dataset dependent",
    licence: "Open Government Licence where marked",
    redistributionPermission: "subject to dataset licence",
    commercialUseStatus: "subject to dataset licence",
    knownLimitations: ["Endpoint and metric coverage change over time"],
    health: "feature-flagged",
  }),
  manifest({
    id: "uk-fsa-alerts",
    name: "UK Food Standards Agency food alerts",
    sourceClass: "authority",
    geographicCoverage: ["United Kingdom"],
    languages: ["en", "cy"],
    dataEventTypes: ["food alerts", "allergy alerts", "recalls"],
    accessMethod: "official API",
    authenticationRequirements: "none",
    cadence: "hourly",
    typicalDelay: "publication dependent",
    licence: "Open Government Licence where marked",
    redistributionPermission: "subject to source licence",
    commercialUseStatus: "subject to source licence",
    knownLimitations: ["Product matching depends on available lot and brand metadata"],
    health: "available",
  }),
  manifest({
    id: "cdc-wastewater",
    name: "CDC public wastewater surveillance",
    sourceClass: "sensor",
    geographicCoverage: ["United States"],
    languages: ["en"],
    dataEventTypes: ["wastewater observations"],
    accessMethod: "Socrata public datasets",
    authenticationRequirements: "none for low-volume access",
    cadence: "dataset dependent",
    typicalDelay: "reporting dependent",
    licence: "US government public data with dataset notes",
    redistributionPermission: "subject to dataset notes",
    commercialUseStatus: "subject to dataset notes",
    knownLimitations: ["Sites and pathogens vary; missingness is expected"],
    health: "feature-flagged",
  }),
  manifest({
    id: "openfda-enforcement",
    name: "openFDA enforcement and recall data",
    sourceClass: "authority",
    geographicCoverage: ["United States"],
    languages: ["en"],
    dataEventTypes: ["food enforcement", "drug enforcement", "device enforcement"],
    accessMethod: "public JSON API",
    authenticationRequirements: "optional API key for higher limits",
    cadence: "API dataset dependent",
    typicalDelay: "reporting dependent",
    licence: "openFDA terms and source data notices",
    redistributionPermission: "subject to openFDA terms",
    commercialUseStatus: "subject to openFDA terms",
    knownLimitations: ["Recall presence does not establish target exposure"],
    health: "feature-flagged",
  }),
  manifest({
    id: "ncbi-entrez",
    name: "NCBI literature and pathogen context",
    sourceClass: "science",
    geographicCoverage: ["global"],
    languages: ["en", "multiple abstracts"],
    dataEventTypes: ["literature", "public biological context"],
    accessMethod: "NCBI E-utilities",
    authenticationRequirements: "optional API key for higher limits",
    cadence: "continuous indexing",
    typicalDelay: "indexing dependent",
    licence: "record-specific",
    redistributionPermission: "record-specific",
    commercialUseStatus: "record-specific",
    knownLimitations: ["Literature is context, not direct evidence of target impact"],
    health: "available",
  }),
  manifest({
    id: "nextstrain",
    name: "Nextstrain public datasets",
    sourceClass: "science",
    geographicCoverage: ["global; dataset dependent"],
    languages: ["en"],
    dataEventTypes: ["phylogenetic context"],
    accessMethod: "public datasets",
    authenticationRequirements: "none",
    cadence: "dataset dependent",
    typicalDelay: "dataset dependent",
    licence: "dataset-specific",
    redistributionPermission: "dataset-specific",
    commercialUseStatus: "dataset-specific",
    knownLimitations: ["Not used for mutation optimisation or pathogen design"],
    health: "feature-flagged",
  }),
  manifest({
    id: "woah-wahis",
    name: "WOAH animal-health information",
    sourceClass: "authority",
    geographicCoverage: ["global"],
    languages: ["en", "fr", "es"],
    dataEventTypes: ["animal disease events"],
    accessMethod: "public portal/document retrieval",
    authenticationRequirements: "none for public materials",
    cadence: "reporting dependent",
    typicalDelay: "member reporting dependent",
    licence: "WOAH terms",
    redistributionPermission: "metadata and lawful excerpts only",
    commercialUseStatus: "verify WOAH terms",
    knownLimitations: ["Reliable machine API is not assumed"],
    health: "feature-flagged",
  }),
  manifest({
    id: "uk-plant-health",
    name: "UK Plant Health Portal notices",
    sourceClass: "authority",
    geographicCoverage: ["United Kingdom"],
    languages: ["en"],
    dataEventTypes: ["plant pest alerts", "plant-health guidance"],
    accessMethod: "public web documents",
    authenticationRequirements: "none",
    cadence: "daily",
    typicalDelay: "publication dependent",
    licence: "source-specific",
    redistributionPermission: "metadata and lawful excerpts only",
    commercialUseStatus: "verify source terms",
    knownLimitations: ["Feature relies on stable public pages"],
    health: "feature-flagged",
  }),
  manifest({
    id: "environment-agency-water",
    name: "Environment Agency flood-monitoring stations",
    sourceClass: "sensor",
    geographicCoverage: ["England"],
    languages: ["en"],
    dataEventTypes: ["station metadata", "flood-monitoring observations"],
    accessMethod: "public data API",
    authenticationRequirements: "none",
    cadence: "dataset dependent",
    typicalDelay: "monitoring dependent",
    licence: "Open Government Licence where marked",
    redistributionPermission: "subject to dataset licence",
    commercialUseStatus: "subject to dataset licence",
    knownLimitations: [
      "The active v1 path validates station metadata; it is not a comprehensive water-quality feed",
    ],
    health: "available",
  }),
  manifest({
    id: "travelhealthpro",
    name: "TravelHealthPro outbreak surveillance",
    sourceClass: "authority",
    geographicCoverage: ["global travel destinations"],
    languages: ["en"],
    dataEventTypes: ["travel-health notices"],
    accessMethod: "public web documents",
    authenticationRequirements: "none",
    cadence: "daily",
    typicalDelay: "publication dependent",
    licence: "source-specific",
    redistributionPermission: "metadata and lawful excerpts only",
    commercialUseStatus: "verify source terms",
    knownLimitations: ["Advice must be confirmed against the current official page"],
    health: "feature-flagged",
  }),
];

export function sourceHealthSummary(): Array<{
  id: string;
  name: string;
  health: SourceManifest["health"];
  limitation?: string;
}> {
  return INITIAL_SOURCE_MANIFESTS.map((item) => ({
    id: item.id,
    name: item.name,
    health: item.health,
    ...(item.knownLimitations[0] ? { limitation: item.knownLimitations[0] } : {}),
  }));
}
